### PR TITLE
Upgrading compiler and dependencies to svelte 3.0

### LINKED ISSUE #2: Does not work with svelte 3.0
This does not work with svelte 3.0.

I plan on submitting a PR soon, but basically the compile function needs to be changed to the new svelte 3.0 compile api

In process version of my updates in case anyone can't wait.
```
compile(args) {
    if (!this.opts.name) this.opts.name = capitalize(sanitize(args.path))

    return svelte.preprocess(args.data, {}).then(result => {
      let {js, css, ast} = svelte.compile(
        result.toString(),
        Object.assign({ filename: args.path }, this.opts)
      )

      if (this.opts.extractCSS && css) {
        this.cssLookup.set(args.path, {
          code: css,
          map: cssMap,
          path: args.path
        })
      }

      return {
        data: js.code,
        map: js.map
      }
    })
  }
```

### PR DESCRIPTION
**Pull request by bakenator**
Made the required changes to use the new Svelte 3.0 release.

Tested working within a Phoenix/Elixir app which uses brunch by default.

fixes https://github.com/StarpTech/sveltejs-brunch/issues/2

### CODE REVIEW

**Comment by StarpTech** [comment]
Hi, could you add a simple test to avoid regressions in the future?

**Comment by bakenator** [comment]
Added a base case test of compiling one file.

**Comment by StarpTech** [comment]
@bakenator thanks, I will review it tomorrow.

**Comment by StarpTech** [comment]
sveltejs-brunch 1.0.0 published 🎉

**Pull request merged**
